spring:
  application:
    name: yupao-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yupao
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER #整合knife4j问题
  # session 失效时间（分钟）
  session:
    timeout: 3600  # 一小时
    store-type: redis

  # redis 配置
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
  profiles:
    active: dev
server:
  port: 7529
  servlet:
    context-path: /api


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    #打印SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

aliyun:
  oss: # OSS
    accessKeyId:
    accessKeySecret:
    bucketName:
  sms: # 短信认证
    regionId:
    accessKeyId:
    secret:
  captcha: #图形认证
    captchaId:
    captchaKey:
    domain:


